"""add grading strictness

Revision ID: 10759db67fcd
Revises: 9f18773a69d4
Create Date: 2026-08-26 10:47:44.621872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '10759db67fcd'
down_revision: Union[str, None] = '9f18773a69d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Phantom ix_notes_ocr_text_fts drop removed again — see e9b8e3c72be7.
    # ### commands auto generated by Alembic - please adjust! ###
    # The enum type has to be created explicitly. Alembic only emits CREATE TYPE as part of
    # create_table — an add_column with sa.Enum assumes the type is already there and fails with
    # "type does not exist". (The mirror image of 9f18773a69d4, where the type DID already exist
    # and the generated sa.Enum had to be told not to create it a second time.)
    strictness = postgresql.ENUM('lenient', 'balanced', 'strict', name='grading_strictness')
    strictness.create(op.get_bind())
    op.add_column(
        'user_settings',
        sa.Column('grading_strictness', strictness, server_default='balanced', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'grading_strictness')
    postgresql.ENUM(name='grading_strictness').drop(op.get_bind())
    # ### end Alembic commands ###
