"""add exams

Revision ID: 25cf09e40b29
Revises: e6eb5b62d9e5
Create Date: 2026-08-28 19:41:05.708260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25cf09e40b29'
down_revision: Union[str, None] = 'e6eb5b62d9e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_user_id'), 'exams', ['user_id'], unique=False)
    op.create_table('exam_decks',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exam_id', 'deck_id')
    )
    # (Stripped the phantom ix_notes_ocr_text_fts drop autogenerate re-emits — it's an expression
    # index Alembic can't reflect; see the note in 10759db67fcd.)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_decks')
    op.drop_index(op.f('ix_exams_user_id'), table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###
