"""add student memory notes

Revision ID: 4d97b779f2f7
Revises: 56863cf8e9ee
Create Date: 2026-08-18 18:12:09.250234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d97b779f2f7'
down_revision: Union[str, None] = '56863cf8e9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_memory_notes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('preference', 'gap', 'context', 'custom', name='memory_category'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'auto', name='memory_source'), server_default='manual', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_memory_notes_user_id'), 'student_memory_notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_memory_notes_user_id'), table_name='student_memory_notes')
    op.drop_table('student_memory_notes')
    # ### end Alembic commands ###

    # op.drop_table() doesn't drop the Postgres ENUM types the columns used — see the init
    # migration for the same fix and why it's needed.
    sa.Enum(name='memory_source').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='memory_category').drop(op.get_bind(), checkfirst=True)
