"""add user settings

Revision ID: 4ecf47e9c5d8
Revises: e9b8e3c72be7
Create Date: 2026-08-26 10:12:11.701054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ecf47e9c5d8'
down_revision: Union[str, None] = 'e9b8e3c72be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # The autogenerated drop of ix_notes_ocr_text_fts was removed here, as warned in
    # e9b8e3c72be7: it's an expression index Alembic can't reflect, so it is re-detected as
    # "removed" on every revision. Running it as generated would silently drop notes search.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('theme', sa.Enum('system', 'light', 'dark', name='theme'), server_default='system', nullable=False),
    sa.Column('accent', sa.String(), nullable=True),
    sa.Column('new_cards_per_day', sa.Integer(), server_default='20', nullable=False),
    sa.Column('session_size', sa.Integer(), server_default='0', nullable=False),
    sa.Column('daily_goal', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
