"""add tutor session voice_id

Revision ID: 56863cf8e9ee
Revises: d55e65652828
Create Date: 2026-08-18 16:39:14.102585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56863cf8e9ee'
down_revision: Union[str, None] = 'd55e65652828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor_sessions', sa.Column('voice_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutor_sessions', 'voice_id')
    # ### end Alembic commands ###
