"""add is_math to cards

The recurring autogenerate false positive on ix_notes_ocr_text_fts is stripped again — see
9196b2b7bb80. Third time; it will keep appearing on every autogenerate run.

Revision ID: 6eae338ee38a
Revises: e5b220505d1f
Create Date: 2026-09-07 12:52:16.893836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eae338ee38a'
down_revision: Union[str, None] = 'e5b220505d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('is_math', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'is_math')
    # ### end Alembic commands ###
