"""add tutor auto memory setting

Revision ID: 73176aa1801b
Revises: 25cf09e40b29
Create Date: 2026-08-28 22:38:18.632593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73176aa1801b'
down_revision: Union[str, None] = '25cf09e40b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (Stripped the phantom ix_notes_ocr_text_fts drop autogenerate re-emits — expression index
    # Alembic can't reflect; see 10759db67fcd.)
    op.add_column('user_settings', sa.Column('tutor_auto_memory', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'tutor_auto_memory')
    # ### end Alembic commands ###
