"""add voice audio settings

Revision ID: 89521913b749
Revises: 10759db67fcd
Create Date: 2026-08-26 13:14:58.467047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89521913b749'
down_revision: Union[str, None] = '10759db67fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Phantom ix_notes_ocr_text_fts drop removed again — see e9b8e3c72be7.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('tts_speed_pct', sa.Integer(), server_default='100', nullable=False))
    op.add_column('user_settings', sa.Column('mic_sensitivity', sa.Integer(), server_default='10', nullable=False))
    op.add_column('user_settings', sa.Column('mic_silence_ms', sa.Integer(), server_default='1500', nullable=False))
    op.add_column('user_settings', sa.Column('push_to_talk', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'push_to_talk')
    op.drop_column('user_settings', 'mic_silence_ms')
    op.drop_column('user_settings', 'mic_sensitivity')
    op.drop_column('user_settings', 'tts_speed_pct')
    # ### end Alembic commands ###
