"""add billing entitlements and credit ledger

Entitlement columns on users, an append-only credit ledger, and the table that makes webhook
delivery idempotent.

Autogenerate also proposed dropping ix_notes_ocr_text_fts. That index is created by an earlier
migration as a raw expression index (GIN over two to_tsvector calls) and has no counterpart in
the model metadata, so every autogenerate run will suggest removing it. It backs the notes search
and is deliberately kept — the drop has been deleted from both directions here.

Revision ID: 9196b2b7bb80
Revises: 89f1e5891a57
Create Date: 2026-09-04 07:09:19.995745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9196b2b7bb80'
down_revision: Union[str, None] = '89f1e5891a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_events',
    sa.Column('stripe_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_events_stripe_id'), 'stripe_events', ['stripe_id'], unique=True)
    op.create_table('credit_ledger',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('stripe_event_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_event_id')
    )
    op.create_index(op.f('ix_credit_ledger_user_id'), 'credit_ledger', ['user_id'], unique=False)
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('text_ai_lifetime', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('text_ai_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_column('users', 'text_ai_expires_at')
    op.drop_column('users', 'text_ai_lifetime')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_index(op.f('ix_credit_ledger_user_id'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_stripe_events_stripe_id'), table_name='stripe_events')
    op.drop_table('stripe_events')
    # ### end Alembic commands ###
