"""add tutor defaults to user settings

Revision ID: 9f18773a69d4
Revises: 4ecf47e9c5d8
Create Date: 2026-08-26 10:31:36.961091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9f18773a69d4'
down_revision: Union[str, None] = '4ecf47e9c5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Phantom ix_notes_ocr_text_fts drop removed again — see e9b8e3c72be7.
    # create_type=False: the tutor_personality enum already exists in Postgres, created with the
    # tutor_sessions table. Autogenerate emits a bare sa.Enum here, which would try to CREATE TYPE
    # a second time and fail — reusing the existing type is the whole point of a shared enum.
    op.add_column('user_settings', sa.Column('tutor_personality', postgresql.ENUM(name='tutor_personality', create_type=False),
                  server_default='direct', nullable=False))
    op.add_column('user_settings', sa.Column('tutor_voice_id', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('tutor_custom_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'tutor_custom_prompt')
    op.drop_column('user_settings', 'tutor_voice_id')
    op.drop_column('user_settings', 'tutor_personality')
    # ### end Alembic commands ###
