"""init

Revision ID: d55e65652828
Revises: 
Create Date: 2026-08-18 12:25:56.237845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd55e65652828'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('google_sub', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('tier', sa.Enum('friend', 'public', name='user_tier'), server_default='friend', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_table('decks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decks_user_id'), 'decks', ['user_id'], unique=False)
    op.create_table('cards',
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('subtopic', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('state', sa.Enum('new', 'learning', 'review', name='card_state'), server_default='new', nullable=False),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviews', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lapses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_deck_id'), 'cards', ['deck_id'], unique=False)
    op.create_table('notes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=True),
    sa.Column('file_type', sa.Enum('image', 'pdf', name='note_file_type'), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_deck_id'), 'notes', ['deck_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('tutor_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=True),
    sa.Column('personality', sa.Enum('strict_socratic', 'direct', 'encouraging', 'terse', 'custom', name='tutor_personality'), nullable=False),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_sessions_deck_id'), 'tutor_sessions', ['deck_id'], unique=False)
    op.create_index(op.f('ix_tutor_sessions_user_id'), 'tutor_sessions', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('wrong_grade', 'malformed_response', 'other', name='feedback_category'), nullable=False),
    sa.Column('raw_model_output', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_card_id'), 'feedback', ['card_id'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('review_logs',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('answer_input', sa.Text(), nullable=False),
    sa.Column('input_mode', sa.Enum('typed', 'voice', name='input_mode'), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('grading_explanation', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_logs_card_id'), 'review_logs', ['card_id'], unique=False)
    op.create_index(op.f('ix_review_logs_user_id'), 'review_logs', ['user_id'], unique=False)
    op.create_table('tutor_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='tutor_message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_messages_session_id'), 'tutor_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutor_messages_session_id'), table_name='tutor_messages')
    op.drop_table('tutor_messages')
    op.drop_index(op.f('ix_review_logs_user_id'), table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_card_id'), table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_card_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_tutor_sessions_user_id'), table_name='tutor_sessions')
    op.drop_index(op.f('ix_tutor_sessions_deck_id'), table_name='tutor_sessions')
    op.drop_table('tutor_sessions')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_deck_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_cards_deck_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_decks_user_id'), table_name='decks')
    op.drop_table('decks')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # op.drop_table() doesn't drop the Postgres ENUM types the columns used — do that explicitly,
    # otherwise a downgrade-then-upgrade cycle fails with "type ... already exists".
    sa.Enum(name='tutor_message_role').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='input_mode').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='feedback_category').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='tutor_personality').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='note_file_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='card_state').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='user_tier').drop(op.get_bind(), checkfirst=True)
