"""add study list

Autogenerate proposed dropping ix_notes_ocr_text_fts again — it is a raw expression index with
no model counterpart, so every run suggests it. Removed from both directions, as in 9196b2b7bb80.

Revision ID: e5b220505d1f
Revises: ebcf488776da
Create Date: 2026-09-06 17:52:35.516362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b220505d1f'
down_revision: Union[str, None] = 'ebcf488776da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_list_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', name='uq_study_list_user_card')
    )
    op.create_index(op.f('ix_study_list_entries_card_id'), 'study_list_entries', ['card_id'], unique=False)
    op.create_index(op.f('ix_study_list_entries_user_id'), 'study_list_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_list_entries_user_id'), table_name='study_list_entries')
    op.drop_index(op.f('ix_study_list_entries_card_id'), table_name='study_list_entries')
    op.drop_table('study_list_entries')
    # ### end Alembic commands ###
