"""add onboarded_at

Revision ID: e6eb5b62d9e5
Revises: 89521913b749
Create Date: 2026-08-26 16:55:45.719456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6eb5b62d9e5'
down_revision: Union[str, None] = '89521913b749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Phantom ix_notes_ocr_text_fts drop removed — see e9b8e3c72be7.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'onboarded_at')
    # ### end Alembic commands ###
