"""add note title

Revision ID: e9b8e3c72be7
Revises: a2088e02c41a
Create Date: 2026-08-26 09:40:11.428755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b8e3c72be7'
down_revision: Union[str, None] = 'a2088e02c41a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('notes', sa.Column('title', sa.String(), nullable=True))
    # NOTE: autogenerate also emitted a drop of ix_notes_ocr_text_fts here and it has been removed
    # deliberately. That index is an expression index over to_tsvector(...), which Alembic cannot
    # reflect, so every autogenerated revision "detects" it as removed. Running it as generated
    # would silently drop notes search. Expect the same phantom drop in future revisions on this
    # table — delete it there too.


def downgrade() -> None:
    op.drop_column('notes', 'title')
