"""add fsrs settings

Revision ID: eadfee81025d
Revises: 73176aa1801b
Create Date: 2026-08-29 09:58:58.535539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eadfee81025d'
down_revision: Union[str, None] = '73176aa1801b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (Phantom ix_notes_ocr_text_fts drop stripped again — see 10759db67fcd.)
    op.add_column('user_settings', sa.Column('fsrs_retention_pct', sa.Integer(), server_default='90', nullable=False))
    op.add_column('user_settings', sa.Column('fsrs_max_interval_days', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'fsrs_max_interval_days')
    op.drop_column('user_settings', 'fsrs_retention_pct')
    # ### end Alembic commands ###
