"""suspend reported cards

Adds cards.suspended and the bad_card feedback category, for the "this card doesn't look right"
report during review.

Two hand-edits to what autogenerate produced. It proposed dropping ix_notes_ocr_text_fts again —
that is the raw expression index behind notes search, it has no model counterpart, and it will be
proposed by every autogenerate run forever (see 9196b2b7bb80). And it did not notice the new
feedback_category value at all: autogenerate does not diff Postgres enum labels, so ADD VALUE is
written by hand, on an autocommit connection because Postgres will not let a label be used in the
transaction that created it.

Revision ID: ebcf488776da
Revises: 9196b2b7bb80
Create Date: 2026-09-04 15:13:03.356509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebcf488776da'
down_revision: Union[str, None] = '9196b2b7bb80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE feedback_category ADD VALUE IF NOT EXISTS 'bad_card'")
    op.add_column('cards', sa.Column('suspended', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'suspended')
    # ### end Alembic commands ###
