"""Request and response bodies, one module per area of the API. Everything is re-exported here,
so `from app.schemas import X` is the one way to reach a schema."""

from app.schemas.admin import (
    ActiveUsersOut,
    AdminStatsOut,
    DailyPointOut,
    FeatureUsageOut,
    LibraryTotalsOut,
    SpendFeatureOut,
    SpendOut,
    UserCountsOut,
)
from app.schemas.bugs import (
    BugReportCreate,
    BugReportOut,
)
from app.schemas.cards import (
    CardCreate,
    CardOut,
    CardUpdate,
    ReviewRequest,
    StudyCardOut,
    StudyQueueOut,
)
from app.schemas.decks import (
    DashboardOut,
    DayDeckOut,
    DeckCreate,
    DeckOut,
    DeckUpdate,
    ImportRequest,
    ImportResult,
)
from app.schemas.exams import (
    ExamCreate,
    ExamOut,
    ExamRef,
    ExamUpdate,
)
from app.schemas.generation import (
    DroppedCardOut,
    GeneratedCardOut,
    GenerateFromNotes,
    GenerateFromTopic,
    GenerationResultOut,
)
from app.schemas.notes import (
    NoteCreate,
    NoteDetailOut,
    NoteOut,
    NoteUpdate,
    UnfileCategory,
    UnfileResult,
)
from app.schemas.settings import (
    SettingsOut,
    SettingsUpdate,
)
from app.schemas.tutor import (
    MemoryNoteCreate,
    MemoryNoteOut,
    MemoryNoteUpdate,
    ProfileLineDelete,
    ProfileLineOut,
    StudentProfileOut,
    TutorMessageOut,
    TutorSessionCreate,
    TutorSessionOut,
    TutorSessionStart,
    TutorSessionUpdate,
    TutorVoiceOut,
    VoiceTurnTextRequest,
)

__all__ = [
    "SpendFeatureOut",
    "SpendOut",
    "ProfileLineDelete",
    "ProfileLineOut",
    "StudentProfileOut",
    "TutorMessageOut",
    "TutorSessionStart",
    "ActiveUsersOut",
    "AdminStatsOut",
    "BugReportCreate",
    "BugReportOut",
    "CardCreate",
    "CardOut",
    "CardUpdate",
    "DailyPointOut",
    "DashboardOut",
    "DayDeckOut",
    "DeckCreate",
    "DeckOut",
    "DeckUpdate",
    "DroppedCardOut",
    "ExamCreate",
    "ExamOut",
    "ExamRef",
    "ExamUpdate",
    "FeatureUsageOut",
    "GenerateFromNotes",
    "GenerateFromTopic",
    "GeneratedCardOut",
    "GenerationResultOut",
    "ImportRequest",
    "ImportResult",
    "LibraryTotalsOut",
    "MemoryNoteCreate",
    "MemoryNoteOut",
    "MemoryNoteUpdate",
    "NoteCreate",
    "NoteDetailOut",
    "NoteOut",
    "NoteUpdate",
    "ReviewRequest",
    "SettingsOut",
    "SettingsUpdate",
    "StudyCardOut",
    "StudyQueueOut",
    "TutorSessionCreate",
    "TutorSessionOut",
    "TutorSessionUpdate",
    "TutorVoiceOut",
    "UnfileCategory",
    "UnfileResult",
    "UserCountsOut",
    "VoiceTurnTextRequest",
]
